import { ROUTES } from '../../constants/routes';

export const routeConfig = {
  public: [ROUTES.LANDING, ROUTES.LOGIN, ROUTES.SIGNUP],
  sharedAuthed: [ROUTES.APP_HOME, ROUTES.ROLE_SELECT, ROUTES.MODERATION_QUEUE],
  client: [ROUTES.CLIENT_ONBOARDING, ROUTES.CLIENT_HOME, ROUTES.CLIENT_JOBS_NEW, ROUTES.CLIENT_JOBS, ROUTES.CLIENT_INBOX, ROUTES.CLIENT_SETTINGS],
  contractor: [ROUTES.CONTRACTOR_ONBOARDING, ROUTES.CONTRACTOR_HOME, ROUTES.CONTRACTOR_FEED, ROUTES.CONTRACTOR_PROFILE, ROUTES.CONTRACTOR_INBOX, ROUTES.CONTRACTOR_SETTINGS],
};
