import { ROUTES } from '../../constants/routes';

export const routeConfig = {
  public: [ROUTES.LANDING, ROUTES.LOGIN, ROUTES.SIGNUP],
  authed: [
    ROUTES.DASHBOARD,
    ROUTES.ROLE_SELECT,
    ROUTES.CUSTOMER_ONBOARDING,
    ROUTES.CONTRACTOR_ONBOARDING,
    ROUTES.CUSTOMER_HOME,
    ROUTES.CONTRACTOR_HOME,
    ROUTES.JOBS_NEW,
    ROUTES.JOBS_MINE,
    ROUTES.FEED,
    ROUTES.CONTRACTOR_PROFILE,
    ROUTES.INBOX,
    ROUTES.SETTINGS,
    ROUTES.MODERATION_QUEUE,
  ],
};
