export const CATEGORY_OPTIONS = [
  'Landscaping',
  'Lawn Care',
  'Snow Removal',
  'Decks and Fences',
  'General Handyman',
  'Plumbing',
  'Electrical',
  'HVAC',
  'Roofing',
  'Siding',
  'Painting',
  'Flooring',
  'Drywall',
  'Renovations',
  'Kitchen and Bath',
  'Concrete',
  'Excavation',
  'Junk Removal',
  'Moving',
  'Cleaning',
  'Window and Door',
  'Tree Services',
  'Pest Control',
  'Appliance Repair',
  'Upholstery',
  'Masonry',
  'Welding and Metalwork',
  'Pool and Spa',
  'Other',
];
